                        
                        <form action="" class="jNice">
                            <h3>Recuperar Clave</h3>
                            <fieldset>
                                <p><label>Email:</label><input type="text" class="text-long" /></p>
                                <input type="submit" value="Entrar" />
                            </fieldset>
                        </form>