            <!-- LOGO -->
            <div class="container">
                <div class="row-fluid">
                    <div class="span3 logo"><img src="<?php echo STAT_URL?>/img/design/logo.fw.png" border="0" /></div>
                    <div class="offset9"></div>
                </div>                
            </div>

            <!-- BARRA DE NAVEGACION -->
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar">s</span>
                            <span class="icon-bar">s</span>
                            <span class="icon-bar">s</span>
                        </a>
                        <a class="brand" href="#">Buscador inmobiliario</a>
                        <div class="nav-collapse">
                            <ul class="nav">
                                <li class="active"><a href="#">Inicio</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Inmuebles <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Casa</a></li>
                                        <li><a href="#">Departamento</a></li>
                                        <li><a href="#">oficina</a></li>
                                        <li><a href="#">Terreno</a></li>
                                        <li class="divider"></li>
                                        <li><a href="#">Alquiler</a></li>
                                        <li><a href="#">Construcci&oacute;n</a></li>
                                    </ul>
                                </li>
                                <li><a href="#">Contactenos</a></li>
                            </ul>
                            <ul class="nav pull-right">
                                <li class="divider-vertical"></li>
                                <li>
                                    <form class="navbar-search pull-left" action="">
                                        <input type="text" class="search-query span2" placeholder="Search">
                                    </form>
                                </li>
                            </ul>
                        </div><!-- /.nav-collapse -->
                    </div>
                </div><!-- /navbar-inner -->
            </div>