            <?php /* Busqueda General, Busqueda por mapa y ultimos inmuebles */ ?>
            <div class="row-fluid">
                <div class="span9">
                    <?php echo $this->partial('index/partials/search.phtml', array()) //Buscador General y por mapa ?>
                </div>
                <div class="span3">
                    <?php echo $this->partial('index/partials/lastAds.phtml', array()) //Ultimos avisos agregados ?>
                </div>
            </div>
            <div class="row-fluid">CASAS <hr /></div>
            <div class="row-fluid">
                <span class="span12">
                    <ul class="thumbnails">
                        <?php $i=1; while($i<=12): //echo "-*-*->".(12%($i-1));?>
                        <li class="span3 <?php if($i>1 and ($i-1)%4==0):?>iniRow<? endif;?>">
                            <div class="thumbnail">
                                <img src="http://placehold.it/260x180" alt="">
                                <div class="caption">
                                    <h5>Etiqueta Thumbnail</h5>
                                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                                    <p><a href="#" class="btn btn-primary">Acción</a> <a href="#" class="btn">Acción</a></p>
                                </div>
                            </div>
                        </li>
                        <?php $i++; endwhile;?>
                    </ul>
                </span>
            </div>