
        <table id="tblMap" align="center" border='0px' cellpadding="0" cellspacing="0">
            <tr id="sels-map">
                <td>
                    <span>Dpto.:</span>
                    <select id="dpto" name="dpto">	    
                        <option value="">Seleccione</option>
                        <?php foreach($this->ubDptos as $r): ?>
                        <option value="<?php echo $r['key']?>"><?php echo $r['value']?></option>
                        <?php endforeach;?>
                    </select>
                </td>
                <td>
                    <span>Prov.:</span>
                    <select id="prov" name="prov">	    
                        <option value="">Seleccione</option>
                    </select>
                </td>
                <td>
                    <span>Dist.:</span>
                    <select id="dist" name="dist">	    
                        <option value="11">Seleccione</option>
                    </select>
                </td>
                <td>
                    <span>Estado:</span>
                    <select name="opc" id="opc">
                        <option value="">Todos</option>
                        <option value="1">Estreno</option>
                        <option value="2">Reventa</option>
                        <option value="3">Construccion</option>
                        <option value="4">Alquiler</option>
                    </select>                                                                  
                </td>
                <td>
                    <span>Tipo:</span>
                    <select name="tipo" id="tipo">
                        <option value="">Todos</option>
                        <option value="1">Casa</option>
                        <option value="2">Casa campo</option>
                        <option value="3">Casa playa</option>
                        <option value="5">Dpto. playa</option>
                        <option value="6">Dpto. Amoblado</option>
                    </select>
                </td>
                <!--td>
                    <span>Precio : </span>
                    <select name="prec" id="prec">
                        <option value="20000">$20,000</option>
                        <option value="20000-50000">$20,000 - $50,000</option>
                        <option value="50000-80000">$50,000 - $80,000</option>
                        <option value="80000-mas">$80,000 - a mas</option>
                    </select>
                </td-->
            </tr>
            <tr><td colspan='5'><div id="gmap"></div></td></tr>
        </table>