                        
                        <form action="" class="jNice">

                            <h3>Another section</h3>
                            <fieldset>
                                <p><label>Sample label:</label><input type="text" class="text-long" /></p>
                                <p><label>Sample label:</label><input type="text" class="text-medium" /><input type="text" class="text-small" /><input type="text" class="text-small" /></p>
                                <p><label>Sample label:</label>
                                    <select>
                                        <option>Select one</option>
                                        <option>Select two</option>
                                        <option>Select tree</option>
                                        <option>Select one</option>
                                        <option>Select two</option>
                                        <option>Select tree</option>
                                    </select>
                                </p>
                                <p><label>Sample label:</label><textarea rows="1" cols="1"></textarea></p>
                                <input type="submit" value="Submit Query" />
                            </fieldset>
                        </form>