                    <div class="tabbable">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#1" data-toggle="tab"><b>Busqueda por Mapa</b></a></li>
                            <li><a href="#2" data-toggle="tab"><b>Busqueda General</b></a></li>
                        </ul>
                        <div class="tab-content">
                            <!-- Busqueda por Mapa -->
                            <div class="tab-pane active" id="1">
                                <p>I'm in Section 1.</p>
                            </div>
                            <!-- Busqueda General -->
                            <div class="tab-pane" id="2">
                                <p>Howdy, I'm in Section 2.</p>
                            </div>
                        </div>
                    </div>