                    <div class="tabbable">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#1" data-toggle="tab"><b>Busqueda por Mapa</b></a></li>
                            <li><a href="#2" data-toggle="tab"><b>Busqueda General</b></a></li>
                        </ul>
                        <div class="tab-content">
                            <!-- Busqueda por Mapa -->
                            <div class="tab-pane active" id="1">
                                <form id="frm-search-gral" class="form-horizontal">
                                    <div class="row-fluid">
                                        <div class="span12">                                          
                                            <label class="lbl-search">Provincia: </label>
                                            <select id="search-prov" name="search-prov">	    
                                                <option value="11">Callao</option>
                                                <option value="12">Bellavista</option>
                                                <option value="13">Ventanilla</option>
                                                <option value="14">La Punta</option>
                                                <option value="15">La Perla</option>
                                            </select>                                            
                                        </div>
                                    </div>
                                    
                                    <div class="row-fluid">
                                        <div class="span12">
                                            <label>Distritos donde buscar:</label>
                                            <div class="row">
                                                <div class="span4">
                                                    <label class="lbl-search">Distrito1: </label>
                                                    <select id="dist1" name="dist1" class="distritos">	    
                                                        <option value="">Seleccionar</option>
                                                    </select>
                                                    <!--span class="help-inline">Error! corrija el texto!.</span-->
                                                </div>
                                                <div class="span4">
                                                    <label class="lbl-search">Distrito2: </label>
                                                    <select id="dist2" name="dist2" class="distritos">	    
                                                        <option value="">Seleccionar</option>
                                                    </select> 
                                                </div>
                                                <div class="span4">
                                                    <label class="lbl-search">Distrito3: </label>
                                                    <select id="dist3" name="dist3" class="distritos" disabled="">	    
                                                        <option value="">Seleccionar</option>
                                                    </select> 
                                                </div>
                                            </div>                                            
                                        </div>
                                    </div>

                                    <div class="row-fluid">
                                        <div class="span12">
                                            <label>Rango de fecha de registro: </label>
                                            <div class="row">
                                                <div id="date-range">
                                                    <div id="date-range-field"><span> </span><a href="#">▼</a></div>
                                                    <div id="datepicker-calendar"></div>
                                                    <div class="alert alert-info">
                                                        <a class="close" href="#">×</a>
                                                        <strong>Nota : </strong>clickear en fecha de inicio y fecha en fin.
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="row-fluid">
                                        <div class="span12">
                                            <label>Estado del inmueble: </label>
                                            <div class="row">
                                                <div class="span3">
                                                    <label class="checkbox inline"> <input type="checkbox" id="" value="option1"> Estreno </label>
                                                </div>
                                                <div class="span3">
                                                    <label class="checkbox inline"> <input type="checkbox" id="" value="option1"> Reventa </label>
                                                </div>
                                                <div class="span3">
                                                    <label class="checkbox inline"> <input type="checkbox" id="" value="option1"> En construcci&oacute;n </label>
                                                </div>
                                                <div class="span3">
                                                    <label class="checkbox inline"> <input type="checkbox" id="" value="option1"> Alquiler </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                    <div class="row-fluid">
                                        <div class="span12">
                                            <label>Rango de fecha de registro: </label>
                                            <div id="tipoInm" class="row">
                                                <div class="span2">
                                                    <label class="checkbox inline"> <input type="checkbox" id="" value="option1"> Casa </label>
                                                </div>
                                                <div class="span2">
                                                    <label class="checkbox inline"> <input type="checkbox" id="" value="option1"> Casa de campo </label>
                                                </div>
                                                <div class="span2">
                                                    <label class="checkbox inline"> <input type="checkbox" id="" value="option1"> Casa de Playa </label>
                                                </div>
                                                <div class="span2">
                                                    <label class="checkbox inline"> <input type="checkbox" id="" value="option1"> Dpto. de Playa </label>
                                                </div>
                                                <div class="span2">
                                                    <label class="checkbox inline"> <input type="checkbox" id="" value="option1"> Dpto. Amoblado </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div> 
                                    <div id="estadoInm" class="row-fluid">
                                        <div class="span10">
                                            <div class="row-fluid row-end">
                                                <div class="span4">
                                                    Ascensor: <select><option>Si</option></select>
                                                </div>
                                                <div class="span4">
                                                    Garage: <select><option>1</option></select>
                                                </div>
                                                <div class="span4">
                                                    Estacionamientos: <select><option>1</option></select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="span2"><input class="btn btn-primary" type="submit" value="BUSCAR"></div>
                                    </div>
                                </form>
                            </div>
                            <!-- Busqueda General -->
                            <div class="tab-pane" id="2">
                                <table id="tblMap" align="center" border='0px' cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td>
                                            <span>Distrito : </span>
                                            <select id="dist" name="dist">	    
                                                <option value="11">Callao</option>
                                                <option value="12">Bellavista</option>
                                                <option value="13">Ventanilla</option>
                                                <option value="14">La Punta</option>
                                                <option value="15">La Perla</option>
                                                <!-- ... Etc Etc ... -->
                                            </select>
                                        </td>
                                        <td>
                                            <span>Opcion : </span>
                                            <select name="opc" id="opc">
                                                <option value="Estreno">Estreno</option>
                                                <option value="Reventa">Reventa</option>
                                                <option value="Alquiler">Alquiler</option>
                                                <!-- ... Etc Etc ... -->
                                            </select>                                                                  
                                        </td>
                                        <td>
                                            <span>Tipo : </span>
                                            <select name="tipo" id="tipo">
                                                <option value="casa">Casa</option>
                                                <option value="dpto">Dpto</option>
                                                <option value="terreno">Terreno</option>
                                            </select>
                                        </td>
                                        <td>
                                            <span>Precio : </span>
                                            <select name="prec" id="prec">
                                                <option value="20000">$20,000</option>
                                                <option value="20000-50000">$20,000 - $50,000</option>
                                                <option value="50000-80000">$50,000 - $80,000</option>
                                                <option value="80000-mas">$80,000 - a mas</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr><td colspan='4'><div id="gmap"></div></td></tr>
                                </table>
                            </div>
                        </div>
                    </div>