<!DOCTYPE html>
<!--[if lt IE 7]><html class="ie6" lang="es"><![endif]-->
<!--[if IE 7]><html class="ie7" lang="es"><![endif]-->
<!--[if IE 8]><html class="ie8" lang="es"><![endif]-->
<!--[if IE 9]><html class="ie9" lang="es"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html lang="es"><!--<![endif]-->
    <head>
        <? echo "\n".$this->partial('portal/head.phtml', array('foo'=>'')) ?>
    </head>
    <body>
        <div class="container">
            
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar">s</span>
                            <span class="icon-bar">s</span>
                            <span class="icon-bar">s</span>
                        </a>
                        <a class="brand" href="#">Nombre proyecto</a>
                        <div class="nav-collapse">
                            <ul class="nav">
                                <li class="active"><a href="#">Inicio</a></li>
                                <li><a href="#">Inmuebles</a></li>
                                <li><a href="#">Contactenos</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Desplegable <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Acción</a></li>
                                        <li><a href="#">otra acción</a></li>
                                        <li><a href="#">Algo más aquí</a></li>
                                        <li class="divider"></li>
                                        <li class="nav-header">Nav header</li>
                                        <li><a href="#">Enlace separado</a></li>
                                        <li><a href="#">Un enlace separado más</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <form class="navbar-search pull-left" action="">
                                <input type="text" class="search-query span2" placeholder="Search">
                            </form>
                            <ul class="nav pull-right">
                                <!--li><a href="#">Enlace</a></li-->
                                <li class="divider-vertical"></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Desplegable <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Acción</a></li>
                                        <li><a href="#">Otra acción</a></li>
                                        <li><a href="#">Algo más aquí</a></li>
                                        <li class="divider"></li>
                                        <li><a href="#">Enlace separado</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div><!-- /.nav-collapse -->
                    </div>
                </div><!-- /navbar-inner -->
            </div>
            
            
            <!--div class="row-fluid">
                <div class="span4">...</div>
                <div class="span8">...</div>
            </div-->
        </div>
        <!-- Contenido de la web -->
        <?php echo $this->layout()->content ?>
        
        <!-- Fin de contenido de la web -->
        <? echo $this->partial('portal/footer.phtml', array('foo2'=>'')) ?>
    </body>
</html>
