<!DOCTYPE html>
<!--[if lt IE 7]><html class="ie6" lang="es"><![endif]-->
<!--[if IE 7]><html class="ie7" lang="es"><![endif]-->
<!--[if IE 8]><html class="ie8" lang="es"><![endif]-->
<!--[if IE 9]><html class="ie9" lang="es"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html lang="es"><!--<![endif]-->
    <head>
        <? echo "\n".$this->partial('portal/head.phtml', array('foo'=>'')) ?>
    </head>
    <body>
        <div class="container">
            <?php echo $this->partial('portal/header.phtml', array()) ?>
            <!-- Contenido de la web -->
            <?php echo $this->layout()->content ?>
            <!-- Fin de contenido de la web -->
            <? echo $this->partial('portal/footer.phtml', array('foo2'=>'')) ?>
        </div>
    </body>
</html>
