                    
                    <div class="mnu-acc well">
                        <ul class="nav nav-list">
                            <li class="nav-header">Acciones</li>
                            <li class="divider"></li>
                            <?php /* $this->plg_acci generado en /plugin/SchemAdmin.php */
                                if($this->plg_acci and !isset($this->errCode)): ?>
                                <?php foreach($this->plg_acci as $acci=>$aVal): $act='';?>
                                <?php if($aVal['active']){$act='class="active"';} echo "\n"; ?>
                                <?php $pageYCant=($this->ctrl=='inmuebles' && $acci=='index')?'/1/5':''?>
                                <li <?php echo $act; ?>>
                                    <a href="/agentes/<?php echo "$this->ctrl/$acci".$pageYCant ?>">
                                        <?php echo $aVal['text']; ?>
                                    </a>
                                </li>
                                <?php endforeach; ?>
                            <?php endif; echo "\n"; ?>
                        </ul>
                    </div>